export enum OrderStatus {
    PENDING = "PENDING",
    PREPARATION = "PREPARATION",
    CANCELED = "CANCELED",
    REJECTED = "REJECTED",
    DELIVERED = "DELIVERED",
    FINALIZED = "FINALIZED",
    READY = "READY",
  }
  